### ISSUE TITLE
Floating point precision

### ISSUE THREAD

**Issue by TomKaltz** [flash-oss/medici#1]
How are you handling floating point precision in this library.  Seems like you're just storing a javascript Number type.  I am pretty sure this will lead to rounding errors when calculating balances.

http://floating-point-gui.de/

**Comment by koresar** [comment]
There is literally one place where is could happen - when we calculate total of all transactions. In the new `medici@v1.0` the place is guarded by a brave `if` statement.

Good news is that `medici` is battle tested (by us). So, pretty sure precision is not an issue as of now.

**Comment by muenzel** [comment]
Thank you for maintaining this lib. I am currently evaluating for production use.
I found the following rounding issue:

![image](https://user-images.githubusercontent.com/16045496/36892711-e7ab9574-1e05-11e8-86e4-6b5d303f3277.png)

`{
      "_id": "5a991a9446fa7c0794a507ab",
      "accounts": "Income",
      "credit": 99.8,
      "debit": 0,
      "book": "test",
      "memo": "Something else",
      "_journal": "5a991a9446fa7c0794a507a9",
      "datetime": "2018-03-02T09:34:12.100Z",
      "__v": 0,
      "approved": true,
      "voided": false,
      "timestamp": "2018-03-02T09:34:12.100Z",
      "account_path": [
        "Income"
      ]
    }`

`{
      "_id": "5a991a9446fa7c0794a507aa",
      "accounts": "Assets:Cash",
      "credit": 0,
      "debit": 99.9,
      "_journal": "5a991a9446fa7c0794a507a9",
      "book": "test",
      "memo": "Something else",
      "datetime": "2018-03-02T09:34:12.100Z",
      "__v": 0,
      "approved": true,
      "voided": false,
      "timestamp": "2018-03-02T09:34:12.100Z",
      "account_path": [
        "Assets",
        "Cash"
      ]
    }`

When I try to debit "0" and credit "0.1" then I get the expected error:

> Journal is invalid. Total is: 0.01
> (node:1940) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 2): Error: INVALID_JOURNAL

Any thoughts on this? And thanks in advance.
Harald

**Comment by koresar** [comment]
Would you be able to:
1) extract the code snippet which reproduces the bug?
2) and create a new issue for the bug.

That would help us significantly.
Thanks!
