### ISSUE TITLE
Missing changelog for 6.0.0

### ISSUE THREAD

**Issue by krtk6160** [flash-oss/medici#101]
I'm assuming 6.0.0 brings support for mongodb version 6, and would like to upgrade to it. It would be great to have a changelog in the readme for 6.0.0 like there is for other versions that has the breaking changes mentioned.

**Comment by koresar** [comment]
Good point regarding MongoDB 6. I'll take a look at that.

Anyhow, a lot of GitHub projects keep their change log in Releases page. Open the home page of this project, click Releases on the right hand side.

Here is the page: https://github.com/flash-oss/medici/releases

**Comment by koresar** [comment]
The support for MongoDB 6.0 was just added and published as medici 6.1. Thanks for you idea!
