### ISSUE TITLE
Value Added Tax

### ISSUE THREAD

**Issue by jabidof** [flash-oss/medici#104]
Hello
Great job!
Does Medici supports multiple VAT?
Thanks

**Comment by Uzlopak** [comment]
Wrong Question. Medici is a Double-entry accounting system. So it is up to you to to implement VAT handling.

**Comment by jabidof** [comment]
> Wrong Question. Medici is a Double-entry accounting system. So it is up to you to to implement VAT handling.

I fully agree!
Was just asking if a method was already implemented, e.g. one like in the Banana desktop software: https://www.banana.ch/en/global in which you can just apply a VAT code on a transaction.
Such a method is very handy as you define your VAT codes (normally there are more than 1) and then you simply apply it.

If someone has developed something with Medici I'd be interested.

**Comment by Uzlopak** [comment]
If you go to the npm page of the medici you can see which packages use medici as dependency. But in my experience medici is usually used in non-public projects so the chance to find some useful packages is imho low.

**Comment by koresar** [comment]
This question is same as:

> Do databases support multiple VAT?

:)

Thanks for the conversation everyone. The question is significantly outside of the Medici scope.

Cheers
