### ISSUE TITLE
Getting Error in Local Dev Server

### ISSUE THREAD

**Issue by Harsh-R-17** [flash-oss/medici#110]
Hello,

I keep getting the below error, when I try to run the example code:

TransactionError: Failure to save journal: Operation medici_transactions.insertMany() buffering timed out after 10000ms
at Entry.commit in medici/build/Entry.js 

The code I'm using is as below:

const { Book } = require("medici");
const journal = new Book("My Book");
const amount = 10000;
await journal.entry("New Entry")
    .debit("Incomes:Sales", amount, {narration: "Debit Entry"})
    .credit("Expenses:Purchases", amount, {narration: "Credit Entry"})
    .commit();

Could you please help me identify what am I doing wrong here?

**Comment by Harsh-R-17** [comment]
tried this but not worked for me, https://github.com/flash-oss/medici/issues/99

**Comment by Uzlopak** [comment]
10000 ms buffering time out is 100% connection issues.

**Comment by Harsh-R-17** [comment]
> 10000 ms buffering time out is 100% connection issues.

await mongoose.connect(connectionString); I used MongoMemoryReplSet to create connectionString, is it right or wrong? it gives me new mongo db URL each time

**Comment by Uzlopak** [comment]
Yeah of course it will create a new connection string. Sry, but we can not support you with basic issues of mongo/mongoose/mongodb :(

**Comment by koresar** [comment]
```js
mongoose.connect('mongodb://localhost/MY_DB_NAME');
```
