### ISSUE TITLE
Voided Transactions & Historical Balances Discussion

### ISSUE THREAD

**Issue by tudorelu** [flash-oss/medici#117]
Hello and thank you for building medici! It has been a great use to me.

I have a use case where I need to have accurate historical balances of accounts, and sometimes may need to void past entries (due to errors).

**After voiding a past entry, _I would assume the historical balance to also change_.** IE the balance of an account 1 second after the initial (voided) entry, to be equal to the balance 1 second before the `datetime` of that journal (as if that initial entry never existed in the first place).

**However this is not the case** with the current implementation of `void` as currently, voiding a journal creates an opposite entry _at the present date_ (`new Date()`), instead of _at the date of the original entry_. 

## Example:
State before the void:
```
// t0: balance of account1 100
// t1: add journal entry crediting 250 to account1
// t2: balance of account1 350
```

**Expected** state after the void:
```
// t0: balance of account1 100
// t1: add journal entry crediting 250 to account1 
// t2: balance of account1 100         <--- this is what I expect
...
// tcurrent: void journal entry at t1
// tcurrent+1: balance of account1 100
```

**Actual** state after the void:
```
// t0: balance of account1 100
// t1: add journal entry crediting 250 to account1 
// t2: balance of account1 350         <--- this is what I get
...
// tcurrent: void journal entry at t1
// tcurrent+1: balance of account1 100
```

I am aware of the difference between `timestamp` (when the journal was inserted) and `datetime` (when the journal happened in reality).

## Questions:
1. Is my use case reasonable? Should I be able to expect to have accurate historical balances that may change if we void transactions?

2. In `book.void` there any reason we pass the null date (which becomes `new Date()`) to the new journal which voids an old journal entry, instead of just passing the date of the original journal (or the millisecond right after it?)

3. Do you see any potential ways of implementing this without changing the code of the library? Should I implement a mechanism for _deleting_ the journals (and transactions) altogether? Besides violating the rules of good bookkeeping, is there any technical reason why we shouldn't delete journal entries and transactions in medici?

4. Assuming answers to 1. and 2. agree with this, are you happy for me to push a fix updating the date of the voiding journal entry to the same date as the original journal entry?

Again, thank you so much for this library, it has saved me hours of work. I really appreciate this small and mighty code base.

**Comment by tudorelu** [comment]
More on this, it doesn't seem like `book` offers an easy way to access journalEntries directly, if I take the _delete_ route. 

I can access transactions via `book.ledger()` and remove them, or just access the medici_journal via mongo directly, bypassing the book API - but not having a direct API just makes me doubt that journals and transactions are intended to be deleted. I am also not using balance snapshots, if this helps (i set `balanceSnapshotSec` to zero).

**Comment by koresar** [comment]
Hi! 

1. Yes. Yes.
2. No reason.
3. Do NOT delete entries. Otherwise, it won't be ledger any more. Technical issue - balance caching. You'd need to clean the collection too.
4. Yes.

Thank you!

**Comment by Uzlopak** [comment]
I have some different thoughts on this. Maybe needs to dependending on your country rules, too. 

Imagine in the real world: Person X orders product A for 100 credits. You need now to move the product A from your assets to the sold assets ledger, person X anticipated payment needs to be booked into receivables. So if person X transfers the money to reduce the receivables and book the incoming money into the cash account or whatever.

If we make a balance after the person ordered but not yet paid, you could say: We have 100 credits in receivables.

Now, person X sends an E-Mail cancelling the purchase. Now the contract is void and you can void the transaction. In legal terms a legal act can be in effect ex tunc (with effect to the past) or ex nunc (with effect from now on). A contract cancellation could be ex tunc, with effect to the past. Is this relevant for the booking? I think not.

Why?

Imagine your booking year ends on 31st october. You get the order of person X on the 31st october and now you close your ledger. And on 1st september you have new books and now the cancellation happens. You cant modify your old ledger, as it closed. 

So it is actually very very very correct that the new void entry has the curent date. 

So: 
I am -1 on voiding by default back to the transaction date. 
I am +1 if you make it viable to set the void date to the transaction via an option. Maybe there is some case, where booking like that makes some kind of sense, and with that option, also that person would be happy.

**Comment by koresar** [comment]
Since I'm not as smart as @Uzlopak let's do what he said. :)

**Comment by edboyle212** [comment]
That's not a technical question it's an accounting question and generally
surging you never delete a transaction you just create a transaction to
offset it so that you have all the history...eg booked revenue at time of
order and booked contra revenue at time of cancellation

**Comment by tudorelu** [comment]
Dear @Uzlopak and @koresar, thank you for getting back to me. 

Okay, it makes perfect sense to add an option for the date when voiding a transaction, to accomodate for different use cases.

For my specific use case there is a third option - changing the date on a journal entry (and underlying transactions), as the date was inputted incorrectly. But this may cause some issues with the balance caching. Let me figure out a solution to my use case and I let you know.

**Comment by koresar** [comment]
> Okay, it makes perfect sense to add an option for the date when voiding a transaction, to accomodate for different use cases.

If so, I'm happy see a tiny little PR for exactly that and nothing else in it. :)

**Comment by tudorelu** [comment]
> 3. Do NOT delete entries. Otherwise, it won't be ledger any more. Technical issue - balance caching. You'd need to clean the collection too.

@koresar Thanks for the answers. I understand this goes against the principles of a ledger. But it may be necessary for our use case.

Just to clarify - if I delete the entry & all transactions involved, and I delete everything in the balances collection, from a purely functional perspective, medici should OK with that DB state?

**Comment by tudorelu** [comment]
I ended up adding the ability to delete journals and transactions. Okay thanks for that guys! I guess we can close this now. Thanks again for your input 🙏

**Comment by Uzlopak** [comment]
Great to hear that you could adapt it for your needs. I would have not added deletion because it basically violates the ledger rules. But hey, we are not accounts ;)
