### ISSUE TITLE
Add transaction level-db support

### ISSUE THREAD

**Issue by nicolasburtey** [flash-oss/medici#23]
Currently, journal/transactions are not added/update with [atomic, database-level transactions](https://mongoosejs.com/docs/transactions.html). This can lead to inconsistency if the database crashes in the middle of a transaction.

**Comment by Uzlopak** [comment]
@clintonb 
@nicolasburtey 
@grinono
@maximkolc
@gaessaki
@simpleicodev
@rafacorcof

A Code Review is more than welcome :) #35

**Comment by koresar** [comment]
Published as `5.0.0-next.0` npm tag:

```
npm i medici@next
```

**Comment by koresar** [comment]
Released as `v5.0.0`.

```
npm i meidici@latest
```
