### ISSUE TITLE
Commit not working

### ISSUE THREAD

**Issue by rohi** [flash-oss/medici#26]
I am trying to run an example with MongoDB back end.

`    const bookDb = new book("MyBook");

    let journal = await bookDb
      .entry("Test Entry")
      .debit("Assets:Receivable", 500, { clientId: "12345" })
      .credit("Income:Rent", 500)
      .commit();`

But I don't see the commit working.
Also is there a way to specify the DB name so as to support multi tenant solution.

An working example on MERN stack would be of great help.

**Comment by koresar** [comment]
What does it mean "commit is not working"? The `journal` variable is empty? Or the db has no data? Or it throws?

Medici is using mongoose.
The DB name is whatever your mongoose is connected to currently.

If you're talking about the collections names - you need to learn how mongoose works. TL;DR: you need to (re)define the schema: https://github.com/flash-oss/medici#customizing-the-transaction-document-schema

Not sure about what other examples are needed. Anyhow, we are welcome PRs if you feel like more examples are needed.

**Comment by rohi** [comment]
"What does it mean "commit is not working"? The journal variable is empty? Or the db has no data? Or it throws?"

The sample code above is from one of the discussions raised here in the forum. Also the assumption I made from that code is that it will create a new transaction entry I hope it is right.

When I mean "commit is not working" it means that it never returned i.e. promise didn't get resolved neither it threw an error.

It is likely that I am missing something I am using Mongo DB version 3.4 and Mongoose version 6.2 does this matter in any way?

"The DB name is whatever your mongoose is connected to currently."
And this is exactly what I assumed when I started working.
But from some reason I never saw relevant tables being created in Mongo DB.

**Comment by koresar** [comment]
Your problem - mongoose is not connected. That's why DB any operations stuck and never finish. that's why you don't see tables created.

With mongoose you need to have only ONE mongoose instance installed and used by your node app.
See how many installations you've got by typing: `npm ls mongoose`

For more information how mongoose work I'd recommend asking questions in StackOverflow: https://stackoverflow.com/questions/tagged/mongoose
