### ISSUE TITLE
Add support for mongoose 6.x

### ISSUE THREAD

**Issue by krtk6160** [flash-oss/medici#30]
Upgrading to mongoose 6.x is breaking medici. All the operations return `buffering timeout` errors.

**Comment by koresar** [comment]
@krtk6160 would you please submit a PR which fully upgrades medici to mongoose v6?

**Comment by Uzlopak** [comment]
@krtk6160 

You are welcome for a Code Review #35

**Comment by koresar** [comment]
Published as `5.0.0-next.0` npm tag:

```
npm i medici@next
```

**Comment by koresar** [comment]
Released as `v5.0.0`.

```
npm i meidici@latest
```
