### ISSUE TITLE
Wrong default for timestamp in transactions schema

### ISSUE THREAD

**Issue by Uzlopak** [flash-oss/medici#31]
I think this line is wrong

https://github.com/flash-oss/medici/blob/9d22ecaa870971acb341936ee251f7f281ba0a03/src/index.js#L25

Should be actually something like () => (new Date())

**Comment by koresar** [comment]
You're right. It doesn't really compile in TypeScript. `Date.now` returns Number, not the Date.

The `mongoose` (and bare JavaScript) though is able to convert Number to Date on the fly. This line of code is quite widespread in codebases which use `mongoose`. It is often used for speed, - when you don't want to create the Date complex object but a simple Number.

But if you strongly believe that we still better change it your way, then please submit a PR. I'd be happy to merge it.

Cheers
