### ISSUE TITLE
Little Confusion in debit function

### ISSUE THREAD

**Issue by Uzlopak** [flash-oss/medici#32]
We push the transaction into the array and later we add meta to the object

https://github.com/flash-oss/medici/blob/master/src/entry.js#L104
https://github.com/flash-oss/medici/blob/master/src/entry.js#L105

In credit we first add meta and later we push it to transactions. 

Probably this is no problem, as we have an Object reference so we still manipulate the object in the array. But I think it is still a code smell.

**Comment by koresar** [comment]
Yeah. Totally agree.
But I can see you have already fixed it in your PR!
Mate, I'm impressed.
![Alt Text](https://media.giphy.com/media/fnK0jeA8vIh2QLq3IZ/giphy.gif)
