### ISSUE TITLE
Timestamp

### ISSUE THREAD

**Issue by Uzlopak** [flash-oss/medici#43]
@koresar

The failed unit test made me thinking. Despite we lost the validation functionality this actually means that you could overwrite the timestamp and set it something in the future or in the past, which would actually violate the "rule of good bookkeeping". Also could mean that a persisted balance could be breaken, by setting a debit into very past.    Didn't thought of it before.

Implicitly allowing to set the timestamp arbitrary is probably not good. 

Maybe add an timestamp attribute to Entry.ts and use it when creating each transaction, thus avoiding diverging timestamps by milliseconds and then in the line before we push the transaction into the transactint array assign the Entry timestamp to the transaction timestamp.

**Comment by Uzlopak** [comment]
Maybe use current date operator?

https://docs.mongodb.com/manual/reference/operator/update/currentDate/

**Comment by koresar** [comment]
Totally makes sense.
Also, I think I removed mongoose validation too early.

On the other hand, we allow overwriting the entire model! This also can be
damaging to the data consistency.
Should we remove this feature as well?

**Comment by koresar** [comment]
Saw your commits. Let's mark this as resolved now.

PS: we need to think of not allowing changing ledger schema.
