### ISSUE TITLE
Database independent - using ORM https://www.prisma.io/

### ISSUE THREAD

**Issue by indrajitsinh** [flash-oss/medici#64]
Thank you for your hard efforts, it's an amazing project 

https://www.prisma.io/  - supports a lot of databases and it would be amazing to use such ORM and make this project independent from the underlying database

**Comment by Uzlopak** [comment]
Yeah, probably a good move.Should still make a benchmark regarding performance. 

If you use old mongodb driver like 3.0.2 then you are like 5 times faster than using the latest driver. Really sad.

**Comment by koresar** [comment]
We have quite some performance MongoDB optimisations done within this project. Moving to Prisma sounds like a task which is very hard to pull off.

I'll close this issue for now. But still waiting for other people contributions.
