### ISSUE TITLE
Mongoose Specify Connection

### ISSUE THREAD

**Issue by aintHuman** [flash-oss/medici#65]
How can I specify the connection to use ? 

For example, when connection is achieved by mongoose.createConnection(...) vs mongoose.connect(...).

The project I am working on makes use of connections returned from the createConnection method, and not via the standard mongoose connection pool. 

Cant find any documentation or outline in your readme on where the connection can be specified

**Comment by koresar** [comment]
Oh, bummer. We don't support connections except the default one. I'm so sorry!

Can you implement a pull request?

**Comment by koresar** [comment]
I'm happy to wait as long as it takes. Feel free to discuss further.

**Comment by HuuTV** [comment]
> Oh, bummer. We don't support connections except the default one. I'm so sorry!
> 
> Can you implement a pull request?

where are create the connection? have a example?

**Comment by Harsh-R-17** [comment]
If i want to connect with my db then how can I achieve this, this my db connection string `mongodb://172.31.5.177:27017/?readPreference=primary&directConnection=true&ssl=false&authMechanism=DEFAULT`

**Comment by Harsh-R-17** [comment]
@koresar If i want to connect with my db then how can I achieve this, this my db connection string `mongodb://***.**.*.***:27017/?readPreference=primary&directConnection=true&ssl=false&authMechanism=DEFAULT`

**Comment by koresar** [comment]
```
mongodb://***.**.*.***:27017/YOU_DATABASE_NAME_HERE_IS_MISSING
```
