### ISSUE TITLE
Set Timestamp for Journal Entry

### ISSUE THREAD

**Issue by aintHuman** [flash-oss/medici#66]
Is it possible to set the timestamp manually for a journal entry ?

**Comment by Uzlopak** [comment]
Why would you like to do this?

**Comment by aintHuman** [comment]
One example, say I take a payment using platform such as Stripe. My system gets a WebHook notification (not guaranteed to be instant) notifying me that the payment was processed. The payload of the WebHook notice contains the timestamp of the actual transaction. I would like to be able to use that timestamp for the journal entry instead of the time when the payload was received. 

Also lets say I do an end of day reconciliation for missing transactions (say a bunch of callbacks fail or don't get transmitted or aren't received etc...), wouldn't it be reasonable to make the journal entries reflect the time of the transaction, not the time of the reconciliation process ?

**Comment by Uzlopak** [comment]
The timestamp is the technical date, when the information was technically stored in the database. The datetime field is the general ledger entry date.

**Comment by aintHuman** [comment]
Ok, no problem, so how do you set the datetime field ?

**Comment by Uzlopak** [comment]
Correct

**Comment by aintHuman** [comment]
Thanks mate.

**Comment by koresar** [comment]
Thanks all!
